config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "blackbaud_settings#show"

  resource :blackbaud_settings, only: %i[show create destroy] do
      get :callback, on: :member
  end

  resources :blackbaud_hooks, only: %i(index new create)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blackbaud.rb
class Blackbaud < Integration
  belongs_to :org

  def auth_url(redirect_url)
    oauth_client.auth_code.authorize_url redirect_uri: redirect_url
  end
    
  def exchange_token(code, redirect_url)
    update_attrs oauth_client.auth_code.get_token code, redirect_uri: redirect_url
  end

  private
    
  def update_attrs(oauth_token)
    update access_token:  oauth_token.token,
           refresh_token: oauth_token.refresh_token
  end

 def oauth_client
  OAuth2::Client.new ENV['AUTH_CLIENT_ID'], ENV['AUTH_CLIENT_SECRET'],
        site: 'https://oauth2.sky.blackbaud.com',
        authorize_url: 'https://oauth2.sky.blackbaud.com/authorization',
        token_url: 'https://oauth2.sky.blackbaud.com/token'
  end
end

app/models/integration.rb
class Integration < ApplicationRecord
  belongs_to :org
  has_many :integration_hooks
end

app/models/integration_hook.rb
class IntegrationHook < RestHook
  belongs_to :org
  belongs_to :integration

  validates :event_name, uniqueness: { scope: [:org, :target_url] }

  BB_DONOR_MAPPINGS = {
    defaults: {
      type: 'Individual',
      first: :first_name,
      last: :last_name,
      # email: :email,
      # address: :address,
      # phone: :phone,
      # birthdate: :birthdate,
      # lookup_id: :id
      date_added: :created_at,
      gender: :gender,
      religion: :religion
    },
    hook_url: 'https://api.sky.blackbaud.com/constituent/v1/constituents',
    range: {
      type: %w[Individual Organization],
      first: %i[first_name last_name name nickname],
      last: %i[first_name last_name name nickname],
      gender: %w[Male Female Unknown],
      gives_anonymously: [true, false],
      inactive: [true, false],
    },
    required_params: %i[type last],
    non_editable_params: %i[lookup_id date_added gender email address phone birthdate religion],
    editable_params: %i[type first middle last former_name preferred_name
      gives_anonymously inactive],
    # all_params: %i[type last email first address birthdate deceased former_name gender gives_anonymously
    #     inactive lookup_id marital middle name online_presence phone preferred_name suffix suffix_2
    #     title title_2 primary_addressee primary_salutation birthplace ethnicity income religion
    #     industry matches_gifts matching_gift_per_gift_min matching_gift_per_gift_max matching_gift_total_min
    #     matching_gift_total_max matching_gift_factor matching_gift_notes num_employees is_memorial is_solicitor
    #     no_valid_address receipt_type target date_added requests_no_email import_id],
    # available_keys: %i[id first_name last_name email org_id donations_count created_at updated_at
    #     phone address city state zip_code country employer occupation comment last_donation_at
    #     yearly_receipt_sent_at last_zap_sent_at name support_ticket_url has_anonymous_donation
    #     deleted_at merged_into_donor_id merged_donations merged_plans user_id first_donation_id
    #     country_code salutation nickname gender religion birthdate education_level blocked_at]
  }
end

app/models/org.rb
class Org < ApplicationRecord
  has_one :blackbaud
  has_many :rest_hooks
  has_many :integrations
  has_many :integration_hooks, through: :integrations

  def blackbaud_enabled?
    blackbaud&.active?
  end

  def email_confirmed?
    true
  end
end

app/models/rest_hook.rb
class RestHook < ActiveRecord::Base
  belongs_to :org
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_org_id
  protect_from_forgery

  def current_org_id
    Org.find_or_create_by lookup_id: cookies[:last_session_org_id]
  end

  def error_messages_for(model)
    model.errors.full_messages.join ', '
  end
end

app/controllers/blackbaud_hooks_controller.rb
class BlackbaudHooksController < ApplicationController
  def index
    @blackbaud_hooks = current_org_id.integration_hooks.where(active: true)
  end

  def new
    @blackbaud_hook = current_org_id.integration_hooks.build
  end

  def create
    @integration = current_org_id.integrations.where(active: true, type: 'Blackbaud').first
    @blackbaud_hook = @integration.integration_hooks.build integration_params
    @blackbaud_hook.target_url = IntegrationHook::BB_DONOR_MAPPINGS[:hook_url]
    @blackbaud_hook.org = current_org_id

    if @blackbaud_hook.save
      flash[:notice] = t '.notice'
      redirect_to blackbaud_hooks_path
    else
      flash[:alert] = error_messages_for @blackbaud_hook
      render :new
    end
  end

  private

  def integration_params
    params.require(:integration_hook).permit(:event_name, mapping_fields: {})
  end
end

app/controllers/blackbaud_settings_controller.rb
class BlackbaudSettingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def create
    redirect_to Blackbaud.new.auth_url(callback_blackbaud_settings_url), allow_other_host: true
  end
  
  def callback
    bb = current_org_id.blackbaud || current_org_id.build_blackbaud
    if params[:code].present?
      bb.exchange_token params[:code], callback_blackbaud_settings_url
      current_org_id.blackbaud.update active: true
    end
    redirect_to [:blackbaud_settings]
  end

  def show; end

  def destroy
    current_org_id.blackbaud.update active: false
    redirect_to [:blackbaud_settings]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def switcher(model, attribute, disabled: false, data: nil)
    value = model.send attribute

    button_tag '', name: "#{model.model_name.param_key}[#{attribute}]",
        value:  (value ? :off : :on), disabled: disabled, data: data,
        class: [(value ? :on : :off), :switcher].join(' ')
  end
end

app/views/application/_flash.html.slim
- if notice
  = notice.html_safe

app/views/blackbaud_hooks/_form.html.slim
div
  section
    h2 Donor Hook
    = hidden_field_tag 'integration_hook[event_name]', 'donor'

div#donors_hooks
  section
    h2 Mapping fields
    - IntegrationHook::BB_DONOR_MAPPINGS[:editable_params].each do |editable|
      strong = label_tag editable, editable
      = select_tag "integration_hook[mapping_fields][#{editable}]", \
        options_for_select(IntegrationHook::BB_DONOR_MAPPINGS[:range][editable] || [], \
        IntegrationHook::BB_DONOR_MAPPINGS[:defaults][editable]), include_blank: true
      br
      br

.actions
  = submit_tag

app/views/blackbaud_hooks/index.html.slim
/ = action_title :addons, :blackbaud
h2 Blackbaud hooks
ul#hooks
  - @blackbaud_hooks&.each do |hook|
    li
      span = hook.event_name.titleize

br
.actions
  = link_to "+ New Blackbaud Hook" , new_blackbaud_hook_path, class: 'button'

app/views/blackbaud_hooks/new.html.slim
/ - action_title :addons, :blackbaud

h1 Blackbaud Hook
= form_for @blackbaud_hook, url: blackbaud_hooks_path do |f|
  = render 'form', f: f

app/views/blackbaud_settings/show.html.slim
section
  h3
    | About Blackbaud Integration

  p
    | Raiser's Edge NXT is a cloud-based fundraising and relationship management solution for nonprofits by Blackbaud.
  - if current_org_id.blackbaud_enabled?
    = form_tag [:blackbaud_settings], method: :delete
      h3
        | Disable Blackbaud Integrations
        = switcher current_org_id, :blackbaud_enabled?
    br
    .actions
      = link_to "Blackbaud Hooks", blackbaud_hooks_path, class: 'button'

  - else
    = form_tag [:blackbaud_settings]
      h3
        | Enable Blackbaud Integrations
        = switcher current_org_id, :blackbaud_enabled?, disabled: !current_org_id.email_confirmed?

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DbIntegration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= render 'flash' %>
    <%= yield %>
  </body>
</html>